import { arraySidebar } from "vuepress-theme-hope";

export const web = arraySidebar([
  {
    icon: "hi",
    text: "Foreword",
    prefix: "foreword/",
    children: "structure",
    collapsible: true,
  },
  {
    icon: "guide",
    text: "Guide",
    prefix: "guide/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "HTML",
    icon: "html5",
    prefix: "html/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "CSS",
    icon: "css3",
    prefix: "css/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "JS",
    icon: "javascript",
    prefix: "js/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "ES6",
    icon: "es6",
    prefix: "es6/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "Vue",
    icon: "vue",
    prefix: "vue/",
    // children: "structure",
    children: [
      {
        text: "Hello",
        icon: "hi-1",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "Learn",
        icon: "xuexi",
        prefix: "learn/",
        children: [
          {
            text: "基础",
            icon: "post",
            prefix: "essential/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "深入组件",
            icon: "post",
            prefix: "components/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "逻辑复用",
            icon: "post",
            prefix: "reusability/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "内置组件",
            icon: "post",
            prefix: "built-ins/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "应用规范化",
            icon: "post",
            prefix: "scaling-up/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "最佳实践",
            icon: "post",
            prefix: "best-practices/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "TypeScript",
            icon: "post",
            prefix: "typescript/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "进阶主题",
            icon: "post",
            prefix: "extras/",
            children: "structure",
            collapsible: true,
          },
        ],
        collapsible: true,
      },
      {
        text: "Use",
        icon: "use",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "Know",
        icon: "know",
        prefix: "know/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "Love",
        icon: "love",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
    ],
    collapsible: true,
  },
  // {
  //   text: "Node",
  //   icon: "nodejs",
  //   prefix: "html/",
  //   children: "structure",
  //   collapsible: true,
  // },
  // {
  //   text: "Nuxt",
  //   icon: "nuxt",
  //   prefix: "html/",
  //   children: "structure",
  //   collapsible: true,
  // },
  {
    text: "DevTools",
    icon: "tools",
    prefix: "tools/",
    children: [
      {
        text: "Git",
        icon: "git",
        prefix: "git/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "VSCode",
        icon: "vscode",
        prefix: "vscode/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "VSCode Extensions",
        icon: "cj",
        prefix: "vscode_extensions/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "Node Package Manager",
        icon: "package",
        prefix: "package_manage/",
        children: "structure",
        collapsible: true,
      },
    ],
    collapsible: true,
  },
]);
