import { arraySidebar } from "vuepress-theme-hope";

export const web = arraySidebar([
  {
    icon: "hi",
    text: "Foreword",
    prefix: "foreword/",
    children: "structure",
    collapsible: true,
  },
  {
    icon: "guide",
    text: "Guide",
    prefix: "guide/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "HTML",
    icon: "html5",
    prefix: "html/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "CSS",
    icon: "css3",
    prefix: "css/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "JS",
    icon: "javascript",
    prefix: "js/",
    children: [
      {
        text: "概述",
        icon: "zhinanzhen",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "词法结构",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "类型、值和变量",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "表达式和运算符",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "语句",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "对象",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "数组",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "函数",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "类",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "模块",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "标准库",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "迭代器和生成器",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "异步 JavaScript",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "元编程",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "浏览器中的 JavaScript",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "服务器端 JavaScript",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "JavaScript 工具和扩展",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
    ],
    collapsible: true,
  },
  {
    text: "ES6",
    icon: "es6",
    prefix: "html/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "Vue",
    icon: "vue",
    prefix: "vue/",
    // children: "structure",
    children: [
      {
        text: "Hello",
        icon: "post",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "Learn",
        icon: "hot",
        prefix: "learn/",
        children: [
          {
            text: "基础",
            icon: "post",
            prefix: "essential/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "深入组件",
            icon: "post",
            prefix: "components/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "逻辑复用",
            icon: "post",
            prefix: "reusability/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "内置组件",
            icon: "post",
            prefix: "built-ins/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "应用规范化",
            icon: "post",
            prefix: "scaling-up/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "最佳实践",
            icon: "post",
            prefix: "best-practices/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "TypeScript",
            icon: "post",
            prefix: "typescript/",
            children: "structure",
            collapsible: true,
          },
          {
            text: "进阶主题",
            icon: "post",
            prefix: "extras/",
            children: "structure",
            collapsible: true,
          },
        ],
        collapsible: true,
      },
      {
        text: "Use",
        icon: "operate",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "Know",
        icon: "ask",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
      {
        text: "Love",
        icon: "like",
        prefix: "hello/",
        children: "structure",
        collapsible: true,
      },
    ],
    collapsible: true,
  },
  {
    text: "Node",
    icon: "nodejs",
    prefix: "html/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "Nuxt",
    icon: "nuxt",
    prefix: "html/",
    children: "structure",
    collapsible: true,
  },
  {
    text: "DevTools",
    icon: "tools",
    prefix: "html/",
    children: "structure",
    collapsible: true,
  },
]);
