export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"首页","i":"home"},["/index.html","/README.md"]],
  ["v-2d0a776e","/ai/",{"y":"a","t":"Guide","i":"creative"},["/ai/index.html","/ai/README.md"]],
  ["v-2d0a870d","/en/",{"y":"a","t":"Guide","i":"creative"},["/en/index.html","/en/README.md"]],
  ["v-2d0a8026","/cs/",{"y":"a","t":"Guide","i":"creative"},["/cs/index.html","/cs/README.md"]],
  ["v-14e6315a","/life/",{"y":"a","t":"Guide","i":"creative"},["/life/index.html","/life/README.md"]],
  ["v-4c3ee2e0","/slides/about.html",{"y":"s","t":"关于我","i":"slides"},["/slides/about","/slides/about.md"]],
  ["v-ffce0276","/web/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","O":3},["/web/disable","/web/disable.md"]],
  ["v-46a31568","/web/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},["/web/encrypt","/web/encrypt.md"]],
  ["v-206aabf6","/web/markdown.html",{"y":"a","t":"Markdown Enhance","i":"markdown","O":2},["/web/markdown","/web/markdown.md"]],
  ["v-47650056","/web/page.html",{"y":"a","t":"Page Config","i":"page","O":1},["/web/page","/web/page.md"]],
  ["v-6bda0d8c","/ai/web/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","O":3},["/ai/web/disable","/ai/web/disable.md"]],
  ["v-dec5e046","/ai/web/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},["/ai/web/encrypt","/ai/web/encrypt.md"]],
  ["v-15b00021","/ai/web/markdown.html",{"y":"a","t":"Markdown Enhance","i":"markdown","O":2},["/ai/web/markdown","/ai/web/markdown.md"]],
  ["v-278dbbfe","/ai/web/page.html",{"y":"a","t":"Page Config","i":"page","O":1},["/ai/web/page","/ai/web/page.md"]],
  ["v-50d42a4e","/en/web/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","O":3},["/en/web/disable","/en/web/disable.md"]],
  ["v-c3bffd08","/en/web/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},["/en/web/encrypt","/en/web/encrypt.md"]],
  ["v-8ee97b3c","/en/web/markdown.html",{"y":"a","t":"Markdown Enhance","i":"markdown","O":2},["/en/web/markdown","/en/web/markdown.md"]],
  ["v-33c9acc2","/en/web/page.html",{"y":"a","t":"Page Config","i":"page","O":1},["/en/web/page","/en/web/page.md"]],
  ["v-131a91f2","/cs/web/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","O":3},["/cs/web/disable","/cs/web/disable.md"]],
  ["v-4cb6aed6","/cs/web/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},["/cs/web/encrypt","/cs/web/encrypt.md"]],
  ["v-24c9032e","/cs/web/markdown.html",{"y":"a","t":"Markdown Enhance","i":"markdown","O":2},["/cs/web/markdown","/cs/web/markdown.md"]],
  ["v-31ef0449","/cs/web/page.html",{"y":"a","t":"Page Config","i":"page","O":1},["/cs/web/page","/cs/web/page.md"]],
  ["v-11407667","/life/programmer/leijun.html",{"y":"a","t":"雷军","i":"markdown","O":3},["/life/programmer/leijun","/life/programmer/leijun.md"]],
  ["v-7bdab481","/life/programmer/qiubojun.html",{"y":"a","t":"求伯君","i":"markdown","O":2},["/life/programmer/qiubojun","/life/programmer/qiubojun.md"]],
  ["v-7e3b9cab","/life/programmer/wangxiaobo.html",{"y":"a","t":"王小波","i":"markdown","O":1},["/life/programmer/wangxiaobo","/life/programmer/wangxiaobo.md"]],
  ["v-3ca7d2a8","/life/programmer/youyuxi.html",{"y":"a","t":"尤雨溪","i":"markdown","O":4},["/life/programmer/youyuxi","/life/programmer/youyuxi.md"]],
  ["v-adabbb40","/web/css/",{"y":"a","t":"CSS","i":"discover"},["/web/css/index.html","/web/css/README.md"]],
  ["v-ada9f88a","/web/es6/",{"y":"a","t":"ES6","i":"discover"},["/web/es6/index.html","/web/es6/README.md"]],
  ["v-6cb497bf","/web/front/history.html",{"y":"a","t":"Web前端开发简史","i":"markdown","O":2},["/web/front/history","/web/front/history.md"]],
  ["v-7744ae02","/web/front/road.html",{"y":"a","t":"Web前端学习路线","i":"page","O":2},["/web/front/road","/web/front/road.md"]],
  ["v-299948fe","/web/html/disable.html",{"y":"a","t":"Disabling layout and features","i":"config","O":3},["/web/html/disable","/web/html/disable.md"]],
  ["v-9c851bb8","/web/html/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},["/web/html/encrypt","/web/html/encrypt.md"]],
  ["v-189be6ba","/web/html/markdown.html",{"y":"a","t":"Markdown Enhance","i":"markdown","O":2},["/web/html/markdown","/web/html/markdown.md"]],
  ["v-bc6b85cc","/web/html/page.html",{"y":"a","t":"Page Config","i":"page","O":1},["/web/html/page","/web/html/page.md"]],
  ["v-7c610490","/web/html/",{"y":"a","t":"HTML","i":"discover"},["/web/html/index.html","/web/html/README.md"]],
  ["v-62a08be4","/web/javascript/",{"y":"a","t":"Javascript","i":"discover"},["/web/javascript/index.html","/web/javascript/README.md"]],
  ["v-7cb32919","/web/node/",{"y":"a","t":"Javascript","i":"discover"},["/web/node/index.html","/web/node/README.md"]],
  ["v-1ff71564","/web/react/",{"y":"a","t":"Javascript","i":"discover"},["/web/react/index.html","/web/react/README.md"]],
  ["v-ad9a6986","/web/vue/",{"y":"a","t":"Javascript","i":"discover"},["/web/vue/index.html","/web/vue/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},["/404"]],
  ["v-2897d318","/slides/",{"y":"p","t":"Slides"},["/slides/index.html"]],
  ["v-744e6dd4","/web/",{"y":"p","t":"Web"},["/web/index.html"]],
  ["v-2b3cafc9","/ai/web/",{"y":"p","t":"Web"},["/ai/web/index.html"]],
  ["v-075dd7e8","/en/web/",{"y":"p","t":"Web"},["/en/web/index.html"]],
  ["v-b3ccc6fe","/cs/web/",{"y":"p","t":"Web"},["/cs/web/index.html"]],
  ["v-1e86b702","/life/programmer/",{"y":"p","t":"Programmer"},["/life/programmer/index.html"]],
  ["v-0c3aa5fa","/web/front/",{"y":"p","t":"Front"},["/web/front/index.html"]],
]
